buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: SyncReplicasOptimizerHook
  - class: TrainSampleHook
    params:
      every_n_steps: 8000

input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/data/ques_gen_all/data/train/sources.txt
    target_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/data/ques_gen_all/data/train/targets.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/data/ques_gen_all/data/dev/sources.txt
    target_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/data/ques_gen_all/data/dev/targets.txt
