buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: SyncReplicasOptimizerHook
  - class: TrainSampleHook
    params:
      every_n_steps: 1000

input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /home/bigdata/active_project/test_seq2seq_py2/yard_seq2seq/ques_50w/ques_50w_data/train/sources.txt
    target_files:
      - /home/bigdata/active_project/test_seq2seq_py2/yard_seq2seq/ques_50w/ques_50w_data/train/targets.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /home/bigdata/active_project/test_seq2seq_py2/yard_seq2seq/ques_50w/ques_50w_data/dev/sources.txt
    target_files:
      - /home/bigdata/active_project/test_seq2seq_py2/yard_seq2seq/ques_50w/ques_50w_data/dev/targets.txt
