buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: SyncReplicasOptimizerHook
  - class: TrainSampleHook
    params:
      every_n_steps: 4000

#eval_hooks:
#  - class: EvaluationSaveSampleHook
