buckets: 10,20,30,40
hooks:
  - class: PrintModelAnalysisHook
  - class: MetadataCaptureHook
  - class: SyncReplicasOptimizerHook
  - class: TrainSampleHook
    params:
      every_n_steps: 4000

#eval_hooks:
#  - class: EvaluationSaveSampleHook

input_pipeline_train:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/sum_abs_30_100_baseline/data/train/sources_*.txt
    target_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/sum_abs_30_100_baseline/data/train/targets_*.txt

input_pipeline_dev:
  class: ParallelTextInputPipeline
  params:
    source_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/sum_abs_30_100_baseline/data/dev/sources_*.txt
    target_files:
      - /mnt/yardcephfs/mmyard/g_wxg_td_prc/turingli/sum_abs_30_100_baseline/data/dev/targets_*.txt
